name: Docker

on:
  push:
    branches:
      - master
    
    tags:
      - v*
  
  pull_request:

jobs:
  build:
    name: Push to GitHub Package Registry
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: docker.pkg.github.com/${{ github.repository }}
          platforms: linux/amd64
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.MYTOKEN }}
  
